# This serves as build container.
# Without this, all go packages would be downloaded over and over again,
# each time you build the bouncer image.

ARG GOLANG_VERSION=1.21
 
FROM golang:${GOLANG_VERSION}-alpine
 
#RUN apk add --no-cache git

WORKDIR /go/src/app

COPY ./go.mod ./go.mod

RUN go mod download
